Build responsive UI with constraintlayout
corinaorasan171015/ColorMyViews pull request #1
Opened 2021-02-11 07:44 UTC by corinaorasan171015

#### Description
Add more TextViews and three buttons with three different colors and add click handler to color different  three TextViews. The focus is on constraint layout.
#### [Task] 
https://classroom.udacity.com/courses/ud9012/lessons/4f6d781c-3803-4cb9-b08b-8b5bcc318d1c/concepts/152b8298-d6b3-4b29-8edd-1ce13c7c96a6
#### Related PRs
## Steps to Test or Reproduce
1.Start the app.
2.Tap the screen and press the buttons.
## Risks

2021-02-11 08:19 UTC, deniscoman approved these changes

2021-02-11 08:19 UTC, deniscoman commented on app/src/main/java/com/example/colormyviews/MainActivity.kt
> +
We should remove extra line spaces :)

2021-02-11 08:19 UTC, deniscoman commented on app/src/main/java/com/example/colormyviews/MainActivity.kt
> +
Remove extra line

2021-02-11 08:22 UTC, deniscoman requested changes
Can you add another pink button and textView?

2021-02-11 09:14 UTC, AlexandraDamaschin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
We should refactor this and use the from the dimensions file

2021-02-16 09:35 UTC, AlexandraDamaschin approved these changes
Does this improve software quality? Yes

2021-02-16 09:45 UTC, merged